# @name RentCarRequest
POST {{ApiBaseUrl}}{{ApiCarRentalSection}}
Content-Type: application/json
// Usage of variables is also permitted in body definition

{
    "Id": 1,
    "CarId": "{{NewCarId}}",
    "CustomerId": "{{NewCustomerId}}",
    "RentalStart": "2023-08-01",
    "RentalEnd": "2023-08-05",
    "Price": 200.00,
    "Notes": "Rented for a weekend wedding.",
    "NumberOfDrivers": 1
}

###
# @name GetCarRequest
GET {{ApiBaseUrl}}{{ApiCarsSection}}/{{RentCarRequest.request.body.$.CarId}}


