### Add New Car
# @name AddCarRequest
// To use a different authentication provider instead of the default one, specify it using the directive below.
// The provider must be registered beforehand.
// Implicitly registered providers: 'None' (no authentication) and 'OAuth2' (requires prior configuration).
## AUTH-PROVIDER: MyAuth
POST {{ApiBaseUrl}}{{ApiCarsSection}}
Content-Type: application/json

{
    "Id": 6,
    "Brand": "Toyota",
    "Model": "RAV4",
    "EngineType": "2.5 TDI",
    "TransmissionType": "Manual",
    "PeopleCapacity": 7,
    "Color": "silver",
    "Year": 2022,
    "DrivenKilometres": 21000.0,
    "Description": ""
}

### Edit new car
# @name EditCarRequest
// Some test scenarios tend to repeat, therefore there are few directives for in-line testing
## TEST-EXPECT-STATUS: [200, 201]
## TEST-HAS-BODY
// Equals to
## TEST-HAS-BODY: True
## TEST-HAS-HEADER: Content-Type
// Usage of user-defined test directive, registered in 'init.csx':
## TEST-SUCCESSFUL-STATUS: True
PUT {{ApiBaseUrl}}{{ApiCarsSection}}/{{AddCarRequest.request.body.$.Id}}
// You can use request variables also in headers.
Content-Type: {{AddCarRequest.request.headers.Content-Type}}

{
    "Id": 6,
    "Brand": "Toyota",
    "Model": "RAV4",
    "EngineType": "3.0 TDI",
    "TransmissionType": "Manual",
    "PeopleCapacity": 5,
    "Color": "silver",
    "Year": 2022,
    "DrivenKilometres": 21000.0,
    "Description": ""
}

### Get new car
# @name GetEditedCarRequest
# Following directive selects which (already registered) retry strategy should be used.
## RETRY-STRATEGY: Default retry
GET {{ApiBaseUrl}}{{ApiCarsSection}}/{{AddCarRequest.request.body.$.Id}}
