# @name RentCarRequest
POST {{ApiBaseUrl}}{{ApiCarRentalSection}}
Content-Type: application/json
// Usage of variables is also permitted in body definition

{
    "Id": 1,
    "CarId": "{{NewCarId}}",
    "CustomerId": "{{NewCustomerId}}",
    "RentalStart": "2023-08-01",
    "RentalEnd": "2023-08-05",
    "Price": 200.00,
    "Notes": "Rented for a weekend wedding.",
    "NumberOfDrivers": 1
}

###
# Example of all available retry directives. Selected RETRY-STRATEGY must be registered first (via script, see 'demo/init.csx').
# - RETRY-UNTIL-STATUS adds a condition specifying until which status codes retrying should continue.
# - Other retry directives override specific properties of the selected retry strategy.
# - If no retry strategy is explicitly selected, default strategy (possibly overriden by other directives) is used.

## RETRY-STRATEGY: Custom retry
## RETRY-MAX-ATTEMPTS: 5
## RETRY-BACKOFF-TYPE: Linear
## RETRY-MAX-DELAY: 00:00:03
## RETRY-UNTIL-STATUS: [200, 201]
# @name GetCarRequest
GET {{ApiBaseUrl}}{{ApiCarsSection}}/{{RentCarRequest.request.body.$.CarId}}
