// Notice, that this test case doesn't have any pre-request script. ('<test-case-name>-init.csx')

### Add New Car
// Name the request using the metadata line to access its contents later.
# @name AddCarRequest
POST {{ApiBaseUrl}}{{ApiCarsSection}}
Content-Type: application/json
// It is possible to attach body dynamically (by using variables).

{{NewCar}}

### Get New Car
// Separate multiple requests in a single .http file with a line containing '3 hashtags' separator:

# @name GetNewCarRequest
// Access the body and headers of a named request/response using this syntax.
// For JSON bodies, use JPath to retrieve properties. For XML, use XPath.
GET {{ApiBaseUrl}}{{ApiCarsSection}}/{{AddCarRequest.request.body.$.Id}}
