### Add New Car
# @name AddCarRequest
POST {{ApiBaseUrl}}{{ApiCarsSection}}
Content-Type: application/json

{
    "Id": 6,
    "Brand": "Toyota",
    "Model": "RAV4",
    "EngineType": "2.5 TDI",
    "TransmissionType": "Manual",
    "PeopleCapacity": 7,
    "Color": "silver",
    "Year": 2022,
    "DrivenKilometres": 21000.0,
    "Description": ""
}

### Edit new car
# @name EditCarRequest
PUT {{ApiBaseUrl}}{{ApiCarsSection}}/{{AddCarRequest.request.body.$.Id}}
// You can use request variables also in headers.
Content-Type: {{AddCarRequest.request.headers.Content-Type}}

{
    "Id": 6,
    "Brand": "Toyota",
    "Model": "RAV4",
    "EngineType": "3.0 TDI",
    "TransmissionType": "Manual",
    "PeopleCapacity": 5,
    "Color": "silver",
    "Year": 2022,
    "DrivenKilometres": 21000.0,
    "Description": ""
}

### Get new car
# @name GetEditedCarRequest
GET {{ApiBaseUrl}}{{ApiCarsSection}}/{{AddCarRequest.request.body.$.Id}}
