### Add New Car
@hostname=localhost
@port=3001
POST http://{{hostname}}:{{port}}/cars
Content-Type: application/json

{
    "Id": 6,
    "Brand": "Toyota",
    "Model": "RAV4",
    "EngineType": "2.5 TDI",
    "TransmissionType": "Manual",
    "PeopleCapacity": 7,
    "Color": "silver",
    "Year": 2022,
    "DrivenKilometres": 21000.0,
    "Description": ""
}