name: CI/CD Pipeline

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read
  actions: read
  pages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore -warnaserror

    - name: Run Unit tests
      run: dotnet test --no-build --verbosity normal --configuration Release
